### ISSUE TITLE
modffi

### ISSUE THREAD

**Issue by dmazzella** [stinos/micropython#2]
Hi,
i have added support in windows port for modffi.
As main mantainer of windows port i want ask you if my implementation is correct/acceptable.

i have added "libffi_msvc"  from cffi (https://bitbucket.org/cffi/cffi/src/78ceec56f4dc71de69d175d8b2dee782a2da74b2/c/libffi_msvc/?at=default) and "dlfcn" from (https://github.com/dlfcn-win32/dlfcn-win32) for reuse unix/modffi.c

for do this i have modified:

unix/modffi.c:

MSVC strikes again with C99 non-compliance with varlen arrays, switching to use alloca().

232: mp_obj_t pyargs[cif->nargs]; -> mp_obj_t *pyargs = alloca(sizeof(mp_obj_t)*cif->nargs);
236: mp_obj_t res = mp_call_function_n_kw(MP_OBJ_FROM_PTR(func), cif->nargs, 0, pyargs); ->     mp_obj_t res = mp_call_function_n_kw(MP_OBJ_FROM_PTR(func), cif->nargs, 0, *pyargs);
355: ffi_arg values[n_args]; -> ffi_arg *values = alloca(sizeof(ffi_arg)*n_args);
356: void *valueptrs[n_args]; -> void **valueptrs = alloca(sizeof(void *)*n_args);

windows/micropython.vcxproj:

to support "dlfcn"

80: <Link /> -> <Link>
      <AdditionalDependencies>psapi.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
84: <Link /> -> <Link>
      <AdditionalDependencies>psapi.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
 

windows/mpconfigport.h:

added:
171: extern const struct _mp_obj_module_t mp_module_ffi;
175: { MP_ROM_QSTR(MP_QSTR_ffi), MP_ROM_PTR(&mp_module_ffi) }, \

windows/paths.props:

31: <PyIncDirs>$(PyBaseDir);$(PyWinDir);$(PyBuildDir);$(PyWinDir)msvc</PyIncDirs> ->     <PyIncDirs>$(PyBaseDir);$(PyWinDir);$(PyBuildDir);$(PyWinDir)msvc;$(PyWinDir)libffi_msvc</PyIncDirs>

windows/sources.props:

added:
8: <ClCompile Include="$(PyBaseDir)windows\libffi_msvc\*.c" />
14: <ClCompile Include="$(PyBaseDir)unix\modffi.c"/>
38: <ClInclude Include="$(PyBaseDir)windows\libffi_msvc\*.h" />

Any hint on this?

Regards,
D.

**Comment by stinos** [comment]
Looks ok from what I can see, but would be easier if I can inspect the actual diff and test the code myself. Do you have this somewhere in a git branch I can checkout?
Did you add the libraries by itself or the source as a submodule?
In any case: this would definitely be good to get merged into the main branch, ffi can be quite convenient.

**Comment by dmazzella** [comment]
I can clone your repository and add this functionality. ;)

**Comment by stinos** [comment]
Ok, I'll add comments over there

**Comment by stinos** [comment]
It's ok in general and it's actually a realtively small change (to existing code) so I'm +1 on this.
Some things which should be discussed (by main MicroPython maintainers as well, when you make a PR there):
- I'm not sure if there is a convention for how to include external sources in uPy: submodules or just dump code?
- in the latter case: is it ok to just include everything or can we ditch what's not strictly needed (e.g. the README)

Some things which need fixing:
- current ffi tests are written for unix. Either they should be skipped and new tests added for windows, or tests should be modified to open corresponding dll on windows (if that is possible)
- doesn't compile for x64
- breaks mingw builds because mp_module_ffi is added unconditionally in mpconfigport.h, so either you should wrap it with some #ifdef _MSC_VER or figure out how to make it work with mingw as well
- please don't add any build options directly to the vcxproj but add a single AdditionalDependencies line to common.props

**Comment by dmazzella** [comment]
fixed:
- doesn't compile for x64

- please don't add any build options directly to the vcxproj but add a single AdditionalDependencies line to common.props

**Comment by dmazzella** [comment]
i have tried this:

#if defined ( _MSC_VER ) && !defined ( __MINGW32__ )
    extern const struct _mp_obj_module_t mp_module_ffi;
    #define FFI_MODULE    MP_ROM_QSTR(MP_QSTR_ffi), MP_ROM_PTR(&mp_module_ffi) }, \
#else
    #define FFI_MODULE
#endif

#define MICROPY_PORT_BUILTIN_MODULES \
    { MP_OBJ_NEW_QSTR(MP_QSTR_utime), (mp_obj_t)&mp_module_time }, \
    { MP_OBJ_NEW_QSTR(MP_QSTR_umachine), (mp_obj_t)&mp_module_machine }, \
    { MP_OBJ_NEW_QSTR(MP_QSTR_uos), (mp_obj_t)&mp_module_os }, \
    FFI_MODULE \

but i have:
warning C4005: 'FFI_MODULE': macro redefinition
note: see previous definition of 'FFI_MODULE'

any hint?

**Comment by dmazzella** [comment]
fixed:

- breaks mingw builds because mp_module_ffi is added unconditionally in mpconfigport.h, so either you should wrap it with some #ifdef _MSC_VER or figure out how to make it work with mingw as well

**Comment by stinos** [comment]
If I try that code exactly as above there are all kinds of syntax errors; might be because it's not pasted as code though; this seems ok:

```
#ifdef _MSC_VER
extern const struct _mp_obj_module_t mp_module_ffi;
#define FFI_MODULE { MP_ROM_QSTR(MP_QSTR_ffi), MP_ROM_PTR(&mp_module_ffi) }, 
#else
#define FFI_MODULE
#endif

extern const struct _mp_obj_module_t mp_module_os;
extern const struct _mp_obj_module_t mp_module_time;
#define MICROPY_PORT_BUILTIN_MODULES \
    { MP_OBJ_NEW_QSTR(MP_QSTR_utime), (mp_obj_t)&mp_module_time }, \
    { MP_OBJ_NEW_QSTR(MP_QSTR_umachine), (mp_obj_t)&mp_module_machine }, \
    { MP_OBJ_NEW_QSTR(MP_QSTR_uos), (mp_obj_t)&mp_module_os }, \
    FFI_MODULE
```

Note I left out the ```&& !defined(__MINGW32__)```, they should be mutually exclusive.

**Comment by dmazzella** [comment]
fixed with:

#if defined (_MSC_VER) && defined (MICROPY_PY_FFI)
    extern const struct _mp_obj_module_t mp_module_ffi;
    #define MICROPY_PY_FFI_DEF    { MP_ROM_QSTR(MP_QSTR_ffi), MP_ROM_PTR(&mp_module_ffi) },
#else
    #define MICROPY_PY_FFI_DEF
#endif


and defining 

#ifdef _MSC_VER
#define MICROPY_PY_FFI              (1)
#define MICROPY_GCREGS_SETJMP       (1)
#endif


thanks

**Comment by dmazzella** [comment]
remain only to skip tests correctly

**Comment by dmazzella** [comment]
pushed a new commit with:

    if os.name == 'nt':
        skip_tests.add('unix/ffi_callback.py')
        skip_tests.add('unix/ffi_float.py')
        skip_tests.add('unix/ffi_float2.py')

**Comment by dmazzella** [comment]
for test:

import ffi
kernel32 = ffi.open('kernel32')
GetVersion = kernel32.func('I', 'GetVersion', 'v')
dwVersion = 0
dwMajorVersion = 0
dwMinorVersion = 0
dwBuild = 0
dwVersion = GetVersion(None)
dwMajorVersion = dwVersion & 0x00FF
dwMinorVersion = ((dwVersion & 0xFF00) >> 8)
if dwVersion < 0x80000000:
    dwBuild  = ((((dwVersion) >> 16) & 0xFFFF))
print("Version is %d.%d (%d)" % (dwMajorVersion, dwMinorVersion, dwBuild))

**Comment by dmazzella** [comment]
now build for all targets, some hints?

**Comment by stinos** [comment]
- looking at the build output, ffi_getversion test is not included. Might be because it's in windows subdirectory? Even then, I'm not 100% sure the CPython version used in the Appveyor builds has ffi installed so it might still get skipped. But I can fix that myself if needed.
- please move inclusion of the .asm file to sources.props as well: this way, when for instance someone builds a seperate micropython dll and exe, it can be reused easily. Also for now it can be conditionally included based on just platform e.g. just this single line will do:
```
   <MASM Condition="'$(Platform)'=='x64'" Include="libffi_msvc\win64.asm" />
```
- likewise it's probably more interesting to, instead of modifying the original cffi source, just exclude the win32.c file instead. So that gives something like this in sources.props:
```
    <ClCompile Remove="$(PyBaseDir)windows\libffi_msvc\win32.c" Condition="'$(Platform)'=='x64'" />
    <MASM Include="libffi_msvc\win64.asm" Condition="'$(Platform)'=='x64'" />
```
- I assume that instead of ```#if defined (_MSC_VER) && defined (MICROPY_PY_FFI)``` just ```#if MICROPY_PY_FFI``` can be used now? Otherwise it would have to be changed again if it gets enabled for mingw. That's also more similar to the unix port then.

**Comment by dmazzella** [comment]
with vs2015 i have error in load project using:

    <ClCompile Remove="$(PyBaseDir)windows\libffi_msvc\win32.c" Condition="'$(Platform)'=='x64'" />
    <MASM Include="libffi_msvc\win64.asm" Condition="'$(Platform)'=='x64'" />

instead i have used:

    <ClCompile Include="$(PyBaseDir)windows\libffi_msvc\win32.c" Condition="'$(Platform)'=='x64'" >
        <ExcludedFromBuild>true</ExcludedFromBuild>
    </ClCompile>
    <MASM Include="libffi_msvc\win64.asm" Condition="'$(Platform)'=='x64'" />

**Comment by dmazzella** [comment]
committed and pushed with your suggestions

**Comment by dmazzella** [comment]
about:

looking at the build output, ffi_getversion test is not included. Might be because it's in windows subdirectory? Even then, I'm not 100% sure the CPython version used in the Appveyor builds has ffi installed so it might still get skipped. But I can fix that myself if needed.

i have added 'windows' in test_dirs

**Comment by dmazzella** [comment]
ffi_gerversion.py failed, how i can see the output?

**Comment by stinos** [comment]
If you build/test locally you'll get a ffi_getversion.out file showing actual output. If you want to see what happens for the Appveyor build you'd have to follow instructions like these: https://www.appveyor.com/docs/how-to/rdp-to-build-worker.

> with vs2015 i have error in load project using:

strange, I'll see if I can figure out why. But yes ExcludedFromBuild trick does the same basically.

**Comment by dmazzella** [comment]
fixed test

**Comment by stinos** [comment]
Looking good, minor things left:
- there's still a leftover `#ifndef _WIN64` in win32.c, that's not needed anymore now
- in modffi.c there's missing spaces arounf the ```*``` in the alloca arguments
- after squashing everything the .vcxproj now has 2 lines deleted unnecessarily

While I trust this works it might be interesting to have more tests. I tried the ffi_callback.py test for instance and with some modifications it works:
```
libc = ffi_open(('libc.so', 'libc.so.0', 'libc.so.6', 'libc.dylib',
 'MSVCR120.DLL', 'API-MS-WIN-CRT-UTILITY-L1-1-0.DLL', 'ucrtbase.dll'))

qsort = libc.func("v", "qsort", "pllp" if sys.maxsize > 2147483647 and sys.platform == 'win32' else "piip")
```
It's a bit ugly because between all CRT versions uPy supports, MS changed their mind on the implementation each time.. But more problematic is the need for 'pllp' on 64bit windows versions: qsort's argument should be pointer-sized, but why can unix get away with 'piip'? I don't have time to look into this further but this probably should be fixed at some point. Also ffi_float tests were ok as well when modified in a similar way. So maybe it's better to modify and include them after all, what do you think?

In any case, as far as I'm concerned this is good to go (after discussion of previous points with core maintainers) so I'd suggest you squash relevant commits and create a PR against the main MicroPython repository.

**Comment by dmazzella** [comment]
i have modified all unix/ffi_*.py tests with your suggestion and now works correctly.
i have removed #ifndef _WIN64 in win32.c

What lines do you refer to?
> - after squashing everything the .vcxproj now has 2 lines deleted unnecessarily

**Comment by dmazzella** [comment]
modified all based on your suggestions and pushed

**Comment by dmazzella** [comment]
> In any case, as far as I'm concerned this is good to go (after discussion of previous points with core maintainers) so I'd suggest you squash relevant commits and create a PR against the main MicroPython repository.

if you want you can rebase all and create a PR against the main MicroPython repository.

i have not more familiarity with git 👎

**Comment by dmazzella** [comment]
ExcludedFromBuild does not work, any suggestion?

**Comment by dmazzella** [comment]
i have used:

```
<Target Name="Remove libffi_msvc win32" BeforeTargets="ClCompile" Condition="'$(Platform)'=='x64'">
    <ItemGroup>
      <ClCompile Remove="$(PyBaseDir)windows\libffi_msvc\win32.c" />
    </ItemGroup>
  </Target>
```

and this work, any hints?

**Comment by stinos** [comment]
This should do it, I'd prefer it over a seperate Target:

```
<ClCompile Include="$(PyBaseDir)windows\libffi_msvc\*.c" Exclude="$(PyBaseDir)windows\libffi_msvc\win32.c" />
<ClCompile Include="$(PyBaseDir)windows\libffi_msvc\win32.c" Condition="'$(Platform)'=='Win32'" />
```


> i have not more familiarity with git

Not tested, but something like this should so it:
add main repo as new remote called 'upstream':
`git remote add upstream git@github.com:micropython/micropython.git`
push your 'ffi' branch to main repo:
`git push upstream ffi`
Then you can create a PR there.

Otherwise I can handle from here, but it will take a couple of days before I have the time and it would make a mess if more commits from you would be required in my PR. And, after all, you wrote all this.

**Comment by dmazzella** [comment]
i have create a PR against the main MicroPython repository

**Comment by stinos** [comment]
PR 3078 for MicroPython is the continuation of this, closing.
